clinica/clinica_integral/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^secretadmin/', admin.site.urls),
    url(r'^auth/', include('myauth.urls')),
    url(r'^', include('integral.urls', namespace='integral')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinica/integral/urls.py
from django.conf.urls import include, url
from .views import PacienteList, PacienteDetail, PacienteDelete,Consulta_Medica, ConsultaDelete, detalleConsulta, nuevaConsulta, Receta_Medica, detalleRecetas, detalleReceta, nuevaReceta, antecedentes, detalleAntecedente, nuevoAntecedente
from .views import index, nuevoPaciente, expediente


urlpatterns = [
	url(r'^$', index, name = 'index'),
	url(r'^pacientes$', PacienteList.as_view(), name='listarPaciente'),
	#url(r'^listarAntecedentes/(?P<expedienteId>\d+)$', AntecedenteList, name='listarAntecedentes'),
	url(r'^detallePaciente/(?P<pk>\d+)$', PacienteDetail.as_view(), name='detallePaciente'),
	url(r'^eliminarPaciente/(?P<pk>\d+)$', PacienteDelete.as_view(), name='eliminarPaciente'),
	# url(r'^eliminarConsulta/(?P<pk>\d+)$', ConsultaDelete.as_view(), name='eliminarConsulta'),
	url(r'^nuevoPaciente/$', nuevoPaciente, name='nuevoPaciente'),
	url(r'^expediente/$', expediente, name = 'expedientes'),
	url(r'^ConsultasMedica/(?P<expedienteId>\d+)/$',Consulta_Medica, name='ConsultaMedica'),
	url(r'^detalleConsulta/(?P<consultaId>\d+)/(?P<expedienteId>\d+)$', detalleConsulta, name='detalle_Consulta'),
	url(r'^nuevaConsulta/(?P<expedienteId>\d+)$', nuevaConsulta, name='nuevaConsulta'),
	url(r'^RecetasMedica/(?P<consultaId>\d+)/$',Receta_Medica, name='RecetaMedica'),
	url(r'^detalleReceta/(?P<recetaId>\d+)/(?P<consultaId>\d+)$', detalleReceta, name='detalle_Consulta'),
	url(r'^detalleRecetas/(?P<consultaId>\d+)$', detalleRecetas, name='detalle_Consultas'),
	url(r'^nuevaReceta/(?P<consultaId>\d+)$', nuevaReceta, name='nuevaReceta'),
	url(r'^antecedentes/(?P<expedienteId>\d+)/$',antecedentes, name='antecedentes'),
	url(r'^detalleAntecedente/(?P<antecedenteId>\d+)/(?P<expedienteId>\d+)$', detalleAntecedente, name='detalle_antecedente'),
	url(r'^nuevoAntecedente/(?P<expedienteId>\d+)$', nuevoAntecedente, name='nuevoAntecedente'),
]

clinica/myauth/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),

    url(r'^settings/$', views.settings, name='settings'),
    url(r'^settings/password/$', views.password, name='password'),
]

clinica/templates/base.html
{% load static %}
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<!--
	Transit by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Clinica Medica Integral</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/skel.min.js' %}" ></script>
		<script src="{% static 'js/skel-layers.min.js' %}"></script>
		<script src="{% static 'js/init.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/skel.css' %}" />
		<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
		<link rel="stylesheet" href="{% static 'css/style-xlarge.css' %}" />
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<h1><a href="/">Clinica Medica Integral</a></h1>
				<nav id="nav">
					<ul>
						<li><a href="/">Inicio</a></li>
						<li><a href="{% url 'integral:listarPaciente' %}">Pacientes</a></li>
						<li><a href="{% url 'integral:expedientes' %}">Expedientes</a></li>
						{% if user.is_authenticated %}
						<li><a href="{% url 'logout' %}" class="button special">Cerrar Sesion</a></li>
						{% else %}
						<li><a href="{% url 'login' %}" class="button special">IniciarSesion</a></li>
						{% endif %}
					</ul>
				</nav>
			</header>

			{% block  content %}
			{% endblock %}
			{% block body %}
			{% endblock %}


		<!-- Footer -->
		<!--	<footer id="footer">
				<div class="container">
					<section class="links">
						<div class="row">
							<section class="3u 6u(medium) 12u$(small)">
								<h3>Lorem ipsum dolor</h3>
								<ul class="unstyled">
									<li><a href="#">Lorem ipsum dolor sit</a></li>
									<li><a href="#">Nesciunt itaque, alias possimus</a></li>
									<li><a href="#">Optio rerum beatae autem</a></li>
									<li><a href="#">Nostrum nemo dolorum facilis</a></li>
									<li><a href="#">Quo fugit dolor totam</a></li>
								</ul>
							</section>
							<section class="3u 6u$(medium) 12u$(small)">
								<h3>Culpa quia, nesciunt</h3>
								<ul class="unstyled">
									<li><a href="#">Lorem ipsum dolor sit</a></li>
									<li><a href="#">Reiciendis dicta laboriosam enim</a></li>
									<li><a href="#">Corporis, non aut rerum</a></li>
									<li><a href="#">Laboriosam nulla voluptas, harum</a></li>
									<li><a href="#">Facere eligendi, inventore dolor</a></li>
								</ul>
							</section>
							<section class="3u 6u(medium) 12u$(small)">
								<h3>Neque, dolore, facere</h3>
								<ul class="unstyled">
									<li><a href="#">Lorem ipsum dolor sit</a></li>
									<li><a href="#">Distinctio, inventore quidem nesciunt</a></li>
									<li><a href="#">Explicabo inventore itaque autem</a></li>
									<li><a href="#">Aperiam harum, sint quibusdam</a></li>
									<li><a href="#">Labore excepturi assumenda</a></li>
								</ul>
							</section>
							<section class="3u$ 6u$(medium) 12u$(small)">
								<h3>Illum, tempori, saepe</h3>
								<ul class="unstyled">
									<li><a href="#">Lorem ipsum dolor sit</a></li>
									<li><a href="#">Recusandae, culpa necessita nam</a></li>
									<li><a href="#">Cupiditate, debitis adipisci blandi</a></li>
									<li><a href="#">Tempore nam, enim quia</a></li>
									<li><a href="#">Explicabo molestiae dolor labore</a></li>
								</ul>
							</section>
						</div>
					</section>
					<div class="row">
						<div class="8u 12u$(medium)">
							<ul class="copyright">
								<li>&copy; Untitled. All rights reserved.</li>
								<li>Design: <a href="http://templated.co">TEMPLATED</a></li>
								<li>Images: <a href="http://unsplash.com">Unsplash</a></li>
							</ul>
						</div>
						<div class="4u$ 12u$(medium)">
							<ul class="icons">
								<li>
									<a class="icon rounded fa-facebook"><span class="label">Facebook</span></a>
								</li>
								<li>
									<a class="icon rounded fa-twitter"><span class="label">Twitter</span></a>
								</li>
								<li>
									<a class="icon rounded fa-google-plus"><span class="label">Google+</span></a>
								</li>
								<li>
									<a class="icon rounded fa-linkedin"><span class="label">LinkedIn</span></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</footer>-->

	</body>
</html>