clinica/clinica_integral/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^secretadmin/', admin.site.urls),
    url(r'^auth/', include('myauth.urls')),
    url(r'^', include('integral.urls', namespace='integral')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinica/integral/urls.py
from django.conf.urls import include, url
from .views import PacienteList, PacienteDetail, PacienteDelete,Consulta_Medica, ConsultaDelete, detalleConsulta, nuevaConsulta, Receta_Medica, detalleRecetas, detalleReceta, nuevaReceta, antecedentes, detalleAntecedente, nuevoAntecedente
from .views import index, nuevoPaciente, expediente


urlpatterns = [
	url(r'^$', index, name = 'index'),
	url(r'^pacientes$', PacienteList.as_view(), name='listarPaciente'),
	#url(r'^listarAntecedentes/(?P<expedienteId>\d+)$', AntecedenteList, name='listarAntecedentes'),
	url(r'^detallePaciente/(?P<pk>\d+)$', PacienteDetail.as_view(), name='detallePaciente'),
	url(r'^eliminarPaciente/(?P<pk>\d+)$', PacienteDelete.as_view(), name='eliminarPaciente'),
	# url(r'^eliminarConsulta/(?P<pk>\d+)$', ConsultaDelete.as_view(), name='eliminarConsulta'),
	url(r'^nuevoPaciente/$', nuevoPaciente, name='nuevoPaciente'),
	url(r'^expediente/$', expediente, name = 'expedientes'),
	url(r'^ConsultasMedica/(?P<expedienteId>\d+)/$',Consulta_Medica, name='ConsultaMedica'),
	url(r'^detalleConsulta/(?P<consultaId>\d+)/(?P<expedienteId>\d+)$', detalleConsulta, name='detalle_Consulta'),
	url(r'^nuevaConsulta/(?P<expedienteId>\d+)$', nuevaConsulta, name='nuevaConsulta'),
	url(r'^RecetasMedica/(?P<consultaId>\d+)/$',Receta_Medica, name='RecetaMedica'),
	url(r'^detalleReceta/(?P<recetaId>\d+)/(?P<consultaId>\d+)$', detalleReceta, name='detalle_Consulta'),
	url(r'^detalleRecetas/(?P<consultaId>\d+)$', detalleRecetas, name='detalle_Consultas'),
	url(r'^nuevaReceta/(?P<consultaId>\d+)$', nuevaReceta, name='nuevaReceta'),
	url(r'^antecedentes/(?P<expedienteId>\d+)/$',antecedentes, name='antecedentes'),
	url(r'^detalleAntecedente/(?P<antecedenteId>\d+)/(?P<expedienteId>\d+)$', detalleAntecedente, name='detalle_antecedente'),
	url(r'^nuevoAntecedente/(?P<expedienteId>\d+)$', nuevoAntecedente, name='nuevoAntecedente'),
]

clinica/myauth/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),

    url(r'^settings/$', views.settings, name='settings'),
    url(r'^settings/password/$', views.password, name='password'),
]

clinica/integral/forms.py
from django import forms
from .models import Paciente, Expediente, Antecedente, ConsultaMedica, Receta, Antecedente


class nuevoPacienteForm(forms.ModelForm):
	class Meta:
		model = Paciente
		fields = [
			'nombre',
			'apellido',
			'sexo',
			'fecha_nacimiento',
			'telefono',
			'direccion',
		]
		labels = {
			'nombre': 'Nombres',
			'apellido': 'Apellidoss',
			'sexo': 'Sexo',
			'fecha_nacimiento': 'Fecha de nacimiento',
			'telefono': 'Teléfono',
			'direccion': 'Dirección',
		}
		widget = {
			'nombre': forms.TextInput(),
			'apellido': forms.TextInput(),
			'sexo': forms.RadioSelect(),
			'fecha_nacimiento': forms.DateInput(),
			'telefono': forms.TextInput(),
			'direccion': forms.Textarea(),
		}


class nuevoExpedienteForm(forms.ModelForm):
	class Meta:
		model = Expediente
		fields = [
			'paciente',
		]
		labels = {
			'paciente': 'Paciente',
		}
		widget = {
			'paciente': forms.Select(),
		}



class ConsultaForm(forms.ModelForm):
	class Meta:
		model=ConsultaMedica

		fields = [
			'fecha',
			'hora',
			'peso',
			'talla',
			'ta',
			'fc',
			'problema',
			'diagnostico',
			'precio_consulta',
			'fk_consulta_expediente',
			'fecha_prox_control',
			'hora_prox_control',
		]

		labels= {
			'fecha':'Fecha de Consulta',
			'hora':' Hora de Consulta',
			'peso':'Peso',
			'talla':'Talla',
			'ta':'Tension Arterial',
			'fc':'Frecuencia Cardiaca',
			'problema':'Problema',
			'diagnostico':'Diagnostico',
			'precio_consulta':'Precio de Consulta',
			'fk_consulta_expediente':'Expediente Asignado',
			'fecha_prox_control':'Fecha de proximo control',
			'hora_prox_control':'Hora de proximo control',
		}

		widget = {
			'fecha':forms.DateField(),
			'hora':forms.TimeField(),
			'peso':forms.DecimalField(),
			'talla':forms.DecimalField(),
			'ta':forms.TextInput(),
			'fc':forms.DecimalField(),
			'problema':forms.TextInput(),
			'diagnostico':forms.TextInput(),
			'precio_consulta':forms.DecimalField(),
			'fk_consulta_expediente':forms.Select(),
			'fecha_prox_control':forms.DateField(),
			'hora_prox_control':forms.TimeField(),
		}

#RECETA FORM
class RecetaForm(forms.ModelForm):
	class Meta:
		model=Receta

		fields = [
			'fecha',
			'hora',
			'medicamento',
			'indicaciones',
		]

		labels= {
			'fecha':'Fecha de Consulta',
			'hora':' Hora de Consulta',
			'medicamento':'Medicamento',
			'indicaciones':'Indicaciones',
		}

		widget = {
			'fecha':forms.DateField(),
			'hora':forms.TimeField(),
			'medicamento':forms.TextInput(),
			'indicaciones':forms.TextInput(),
		}

#Antecedente_FORM
class AntecedenteForm(forms.ModelForm):
	class Meta:
		model=Antecedente

		fields = [
			'enfermedad',
			'familiar',
			'tratamiento',
			'medicamento_asignado',
		]

		labels= {
			'enfermedad':'Enfermedades que ha padecido',
			'familiar':' Familiar que padece esta enfermedad',
			'tratamiento':'Tratamiento recomendado',
			'medicamento_asignado':'Medicina aplicada',
		}

		widget = {
			'enfermedad':forms.TextInput(),
			'familiar':forms.TextInput(),
			'tratamiento':forms.TextInput(),
			'medicamento_asignado':forms.TextInput(),
		}

clinica/integral/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from .models import Paciente, Expediente, Antecedente, ConsultaMedica, Receta, Antecedente
from .forms import nuevoPacienteForm, nuevoExpedienteForm, ConsultaForm, RecetaForm, AntecedenteForm
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
import json
from django.contrib import messages
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

@login_required
def index(request):
	return render(request, 'integral/index.html',{})


@login_required
def nuevoPaciente(request):
	pacientes = Paciente.objects.all()
	paginator = Paginator(pacientes,15)
	page = request.GET.get('page')
	try:
		pacientes = paginator.page(page)
	except PageNotAnInteger:
		pacientes = paginator.page(1)
	except EmptyPage:
		pacientes = paginator.page(paginator.num_pages)
	if request.method == 'POST':
		form = nuevoPacienteForm(request.POST)
		if form.is_valid():
			form.save()
			ultimoPaciente = Paciente.objects.first()
			Expediente.objects.create(paciente = ultimoPaciente)
			messages.success(request, 'Paciente correctamente guardado!')
			return redirect('integral:listarPaciente')
		else:
			data = json.dumps([v for k , v in form.errors.items()]+[' ¡Error!'])
			return HttpResponse(data, content_type='application/json')
	else:
		form = nuevoPacienteForm()
	return render(request, 'integral/nuevoPaciente.html', {'form': form,'pacientes':pacientes})


@login_required
def expediente(request):
	expedientes = Expediente.objects.all()
	paginator = Paginator(expedientes,15)
	page = request.GET.get('page')
	try:
		expedientes = paginator.page(page)
	except PageNotAnInteger:
		expedientes = paginator.page(1)
	except EmptyPage:
		expedientes = paginator.page(paginator.num_pages)
	if request.method == 'POST':
		form = nuevoExpedienteForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Correctamente guardado!')
			return HttpResponse("GUARDADO!")
		else:
		    data = json.dumps([v for k , v in form.errors.items()]+[' ¡Error!'])
		return HttpResponse(data, content_type='application/json')
	else:
		form = nuevoExpedienteForm()
	return render(request, 'integral/expediente/expediente.html',{'form':form,'expedientes':expedientes})

#def AntecedenteList(request,expedienteId):
#	antecedentes = Antecedente.objects.filter(fk_antecedente_expediente=expedienteId)
#	return render(request, 'integral/antecedente_list.html',{'antecedentes':antecedentes})

class PacienteList(LoginRequiredMixin, ListView):
	model = Paciente


class PacienteDetail(LoginRequiredMixin, DetailView):
	model = Paciente


class PacienteDelete(LoginRequiredMixin, DeleteView):
	model = Paciente
	success_message = "Paciente eliminado correctamente"
	success_url = reverse_lazy('integral:listarPaciente')

	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(PacienteDelete, self).delete(request, *args, **kwargs)


class ConsultaDelete(LoginRequiredMixin, DeleteView):
	model = ConsultaMedica
	success_message = "Consulta eliminada correctamente"

	def get_success_url(self):
		expediente = self.object.fk_consulta_expediente
		return reverse_lazy( 'integral:eliminarConsulta', kwargs={'expedienteId': expediente.id})

	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(ConsultaDelete, self).delete(request, *args, **kwargs)

# class AntecedenteList(ListView):
# model = Antecedente
@login_required
def Consulta_Medica(request,expedienteId):
	consulta = ConsultaMedica.objects.filter(fk_consulta_expediente=expedienteId)
	expediente= expedienteId
	return render(request, 'integral/Consulta_Expediente.html',{'consultaMedica':consulta,'expedienteId':expediente})


@login_required
def detalleConsulta(request,consultaId,expedienteId):
	consulta = ConsultaMedica.objects.filter(id=consultaId)
	datos = Paciente.objects.filter(id=expedienteId)
	nombre = Paciente.objects.get(id=expedienteId)
	expediente=expedienteId
	return render(request, 'integral/consultamedica_detail.html',{'conId':consultaId, 'consultaMedica':consulta,'expedienteId':expediente,'paciente':datos, 'nombre':nombre})


@login_required
def nuevaConsulta(request,expedienteId):
	expediente= expedienteId
	datos = Paciente.objects.get(id=expedienteId)
	if request.method == 'POST':
		ConsultaMedica.objects.create(
			fecha=request.POST['fechaActual'],
			hora=request.POST['horaActual'],
			peso=request.POST['PesoPaciente'],
			talla=request.POST['TallaPaciente'],
			ta=request.POST['TensionArterial'],
			fc=request.POST['FrecuenciaCardiaca'],
			problema=request.POST['ProblemaEnfermedad'],
			diagnostico=request.POST['DiagnosticoEnfermedad'],
			fecha_prox_control=request.POST['fechaProxActual'],
			hora_prox_control =request.POST['horaProxActual'],
			precio_consulta=request.POST['PrecioConsulta'],
			fk_consulta_expediente=Expediente.objects.get(id=request.POST['expediente'])
		)
		messages.success(request, 'Correctamente guardado!')
		return HttpResponse('Datos Almacenados Correctamente')
	return render(request,'integral/nuevaConsulta.html',{'expedienteId':expediente, 'paciente':datos})

# RECETAS VIEWS
@login_required
def Receta_Medica(request,consultaId):
	receta = Receta.objects.filter(fk_receta_consulta=consultaId)
	consulta= ConsultaMedica.objects.get(id=consultaId)
	return render(request, 'integral/Receta_Consulta.html',{'recetaMedica':receta,'consulta':consulta})


@login_required
def detalleReceta(request,recetaId,consultaId):
	receta = Receta.objects.filter(id= recetaId)
	datos = ConsultaMedica.objects.get(id=consultaId)
	expediente = datos.fk_consulta_expediente
	print(expediente.id)
	consulta=consultaId
	return render(request, 'integral/recetamedica_detail.html',{'receta':receta,'consultaId':consulta,'consulta':datos, 'expediente':expediente})


def detalleRecetas(request,consultaId):
	receta = Receta.objects.filter(fk_receta_consulta=consultaId)
	datos = ConsultaMedica.objects.get(id=consultaId)
	expediente = datos.fk_consulta_expediente
	print(expediente.id)
	consulta=consultaId
	return render(request, 'integral/recetamedica_detail.html',{'receta':receta,'consultaId':consulta,'consulta':datos, 'expediente':expediente})


@login_required
def nuevaReceta(request,consultaId):
	consulta = consultaId
	datos = ConsultaMedica.objects.get(id=consultaId)
	print(consultaId)
	if request.method == 'POST':
		Receta.objects.create(
			fk_receta_consulta=ConsultaMedica.objects.get(id=consultaId),
			fecha=request.POST['fechaActual'],
			hora=request.POST['horaActual'],
			medicamento=request.POST['MedicamentoPaciente'],
			indicaciones=request.POST['IndicacionesPaciente'],
		)
		messages.success(request, 'Correctamente guardado!')
		return HttpResponse('Datos Almacenados Correctamente')
	return render(request,'integral/nuevaReceta.html',{'consultaId':consulta, 'consulta':datos})


#Antecedente_views
@login_required
def antecedentes(request,expedienteId):
	antecedente = Antecedente.objects.filter(fk_antecedente_expediente=expedienteId)
	expediente= expedienteId
	datos = Expediente.objects.get(id=expedienteId)
	return render(request, 'integral/Antecedente_Expediente.html',{'antecedentes':antecedente,'expedienteId':expediente, 'expe':datos})


@login_required
def detalleAntecedente(request,antecedenteId,expedienteId):
	antecedente = Antecedente.objects.get(id=antecedenteId)
	datos = Expediente.objects.get(id=expedienteId)
	expediente=expedienteId
	return render(request, 'integral/antecedente_detail.html',{'antecedente':antecedente,'expedienteId':expediente,'paciente':datos})


@login_required
def nuevoAntecedente(request,expedienteId):
	expediente = expedienteId
	if request.method == 'POST':
		Antecedente.objects.create(
			fk_antecedente_expediente=Expediente.objects.get(id=expedienteId),
			enfermedad=request.POST['enfermedad'],
			familiar=request.POST['familiar'],
			tratamiento=request.POST['tratamiento'],
			medicamento_asignado=request.POST['medicamento_asignado'],
		)
		messages.success(request, 'Correctamente guardado!')
		return HttpResponse('Datos Almacenados Correctamente')
	return render(request,'integral/nuevoAntecedente.html',{'expedienteId':expediente})

clinica/integral/templates/integral/Antecedente_Expediente.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<section id="main" class="wrapper">
  <div class="container">
    <header class="major">
      <h3>Antecedentes de {{ expe.paciente}}</h3>
    </header>
    <div class="row 150%">
			<div class="container">
				{% if messages %}
				{% for message in messages %}
				{% if message.tags == 'success' %}
				<p style="color: green"> <u>{{ message }}</u></p>
						{% else %}
				<p style="color: red"><u>{{ message }}</u> </p>
				{% endif %}
				{% endfor %}
				{% endif %}
				{% for error in form.non_field_errors %}
				<div class="alert alert-danger" >
					<strong style="color: red">{{ error|escape }}</strong>
				</div>
				{% endfor %}
				<a class="button" href="/nuevoAntecedente/{{expedienteId}}">Agregar Antecedente</a>
				<hr>
				<table>
					<tr>
						<td>ID</td>
						<td>Enfermedad</td>
						<td>Ver Detalles</td>
					</tr>
					{% for antecedente in antecedentes %}
					<tr>
						<td>{{ antecedente.id}}</td>
						<td>{{antecedente.enfermedad}}</td>
						<td><a class ="button" href="/detalleAntecedente/{{antecedente.id}}/{{expedienteId}}">Ver</a></td>
					</tr>
					{% endfor %}
				</table>
            <a class="button" href="/expediente/">Regresar</a>
		 </div>
    </div>
  </div>
</section>

{% endblock content %}

clinica/integral/templates/integral/Consulta_Expediente.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<section id="main" class="wrapper">
  <div class="container">
    <header class="major">
      <h2>Consultas del paciente</h2>
      <p>Aqui puede ver todas las consultas del paciente y Asignar receta</p>
    </header>
    <div class="row 150%">
			<div class="container">
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'success' %}
        <p style="color: green"> <u>{{ message }}</u></p>
            {% else %}
        <p style="color: red"><u>{{ message }}</u> </p>
        {% endif %}
        {% endfor %}
        {% endif %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger" >
          <strong style="color: red">{{ error|escape }}</strong>
        </div>
        {% endfor %}
				<a class="button" href="/nuevaConsulta/{{expedienteId}}">Agregar Consulta</a>
		    <a  class="button" href="{% url 'integral:expedientes' %}">Regresar</a>
				{% if  consultaMedica%}
				<table>
					<tr>
            <td>#</td>
            <td>Fecha</td>
						<td>Detalle</td>
						<td>Receta</td>

					</tr>
					{% for consulta in consultaMedica%}
					<tr>
            <td>{{consulta.id}}</td>
            <td>{{consulta.fecha}}</td>
						<td><a class="button" href="/detalleConsulta/{{consulta.id}}/{{expedienteId}}">Detalle Consulta</a></td>
						<td><a class="button" href="/nuevaReceta/{{consulta.id}}">Asignar Nueva Receta</a></td>

					</tr>
					{% endfor %}
				</table>
				{% else %}
				<p> <strong> No hay consulta, agrege una nueva. </strong></p>
				{% endif %}

		 </div>
    </div>
  </div>
</section>


{% endblock content %}

clinica/integral/templates/integral/Receta_Consulta.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<section id="main" class="wrapper">
  <div class="container">
    <header class="major">
      <h3>{{ paciente }}</h3>
      <hr>
    </header>
    <div class="row 150%">
			<div class="container">
				{% if messages %}
				{% for message in messages %}
				{% if message.tags == 'success' %}
				<p style="color: green"> <u>{{ message }}</u></p>
						{% else %}
				<p style="color: red"><u>{{ message }}</u> </p>
				{% endif %}
				{% endfor %}
				{% endif %}
				{% for error in form.non_field_errors %}
				<div class="alert alert-danger" >
					<strong style="color: red">{{ error|escape }}</strong>
				</div>
				{% endfor %}
				<a class="button" href="/nuevaReceta/{{consulta.id}}">Agregar Receta Medica</a>
				<table>
					<tr>
						<td>#</td>
						<td>Medicamento</td>
						<td>Ver Detalles</td>
					</tr>
					{% for receta in recetaMedica%}
					<tr>
						<td>{{receta.id}}</td>
						<td><p>{{receta.medicamento}}</p></td>
						<td><a class="button" href="/detalleReceta/{{receta.id}}/{{consulta.id}}">Detalle Receta</a></td>
					</tr>
					{% endfor %}
				</table>

            <a class="button" href="/detalleConsulta/{{consulta.id}}/{{consulta.fk_consulta_expediente.id}}">Regresar</a>
						<a class="button" href="/detalleRecetas/{{consulta.id}}">Imprimir receta completa</a>
		 </div>
    </div>
  </div>
</section>


{% endblock content %}

clinica/integral/templates/integral/antecedente_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<section id="main" class="wrapper">
  <div class="container">
    <header class="major">
      <h3>Antecedente de {{ paciente.paciente }}</h3>
      <hr>
    </header>
    <div class="row 150%">
			<div class="container">
        <ul class="alt">
					<table>
						<tr>
							<td><b>Paciente</b></td>
							<td><b>Enfermedad</b></td>
							<td><b>Familiar con misma Enfermedad</b></td>
							<td><b>Tratamiento</b></td>
							<td><b>Medicamento</b></td>
						</tr>
						<tr>
						<td>{{pacienteDato}}</td>
						<td>{{antecedente.enfermedad}}</td>
						<td>{{antecedente.familiar}}</td>
						<td>{{antecedente.tratamiento}}</td>
						<td>{{antecedente.medicamento_asignado}}</td>
						</tr>

					</table>

					<a class="button" href="/antecedentes/{{expedienteId}}/">Regresar</a>
    </div>
  </div>
</section>

{% endblock content %}

clinica/integral/templates/integral/consultamedica_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<section id="main" class="wrapper">
  <div class="container">
    <header class="major">
      <h3>Paciente: {{ nombre }}</h3>
      <hr>
    </header>
    <div class="row 150%">
			<div class="container">
				<table>
					<tr>
						<td><b>Paciente</b></td>
						<td><b>Consulta</b></td>
						<td><b>Fecha</b></td>
						<td><b>Hora</b></td>
						<td><b>Peso</b></td>
						<td><b>Talla</b></td>
						<td><b>Tension Arterial</b></td>
						<td><b>Frecuencia Cardiaca</b></td>
						<td><b>Problema</b></td>
						<td><b>Diagnostico</b></td>

					</tr>


				{% for detalle in consultaMedica %}
				{% for pacienteDato in paciente %}

					<tr>
					<td>{{pacienteDato}}</td>
					<td>{{detalle.id}}</td>
					<td>{{detalle.fecha}}</td>
					<td>{{detalle.hora}}</td>
					<td>{{detalle.peso}}</td>
					<td>{{detalle.talla}}</td>
					<td>{{detalle.ta}}</td>
					<td>{{detalle.fc}}</td>
					<td>{{detalle.problema}}</td>
					<td>{{detalle.diagnostico}}</td>
					</tr>
				</table>
					<h3>Proximo Control:</h3>
					<ul class="alt">
						<li>Hora:{{detalle.hora_prox_control}}</li>
						<li>Fecha: {{detalle.fecha_prox_control}}</li>
					</ul>
					<p><strong>Precio Consulta: {{detalle.precio_consulta}}</strong></p>
				<a class="button" href="/ConsultasMedica/{{expedienteId}}/">Regresar</a>
				<a class="button" href="/RecetasMedica/{{conId}}/">Ver Receta</a>
				{% endfor %}
				{% endfor %}
		 </div>
    </div>
  </div>
</section>




{% endblock content %}

clinica/integral/templates/integral/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<!-- Banner -->
	<section id="banner">
		<h2>Clinica Medica Integral</h2>
		<p>¡Bienvenido!</p>
	</section>

<!-- One -->
	<section id="one" class="wrapper style1 special">
		<div class="container">
			<header class="major">
				<h2>Menú</h2>
				<p>Selecciones una acción:</p>
			</header>
			<div class="row 150%">
				<div class="6u 12u$(medium)">
					<section class="box">
						<i class="icon big rounded color1 fa-cloud"></i>
						<h3>Pacientes</h3>
						<p>Ver, agregar o eliminar pacientes</p>
						<a class="button" href="{% url 'integral:listarPaciente' %}">Pacientes</a>
					</section>
				</div>
				<div class="6u 12u$(medium)">
					<section class="box">
						<i class="icon big rounded color9 fa-desktop"></i>
						<h3>Expedientes</h3>
						<p>Ver consultas y antecedentes de los pacientes</p>
						<a class="button" href="{% url 'integral:expedientes' %}">Expedientes</a>
					</section>
				</div>
			</div>
		</div>
	</section>

{% endblock content %}

clinica/integral/templates/integral/nuevoPaciente.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<section id="main" class="wrapper">
  <div class="container">
    <header class="major">
      <h2>Ingrese un nuevo paciente</h2>
      <p>Llene todos los datos correctamente</p>
    </header>
    <div class="row 150%">
			<div class="container">
		    <a  class="button" href="{% url 'integral:listarPaciente' %}">Regresar</a>
					<div id="nuevoPacient">
						<form action="" method="post" id="nuevoPacienteForm">
							{% csrf_token %}
							{{form.as_p}}
							<input type="submit" value="Guardar" id="btnGuardarPaciente">
						</form>
					</div>
		        <div id="asigExp"></div>
				<div id="antecedentes"></div>
		 </div>
    </div>
  </div>
</section>

{% endblock content %}

clinica/integral/templates/integral/paciente_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<section id="main" class="wrapper">
  <div class="container">
    <header class="major">
      <h2>Pacientes</h2>
      <p>Aqui puede ver los pacientes:</p>
    </header>
    <div class="row 150%">
      {% if messages %}
      {% for message in messages %}
      {% if message.tags == 'success' %}
      <p style="color: green"> <u>{{ message }}</u></p>
          {% else %}
      <p style="color: red"><u>{{ message }}</u> </p>
      {% endif %}
      {% endfor %}
      <p></p>
      {% endif %}
      <div class="table-wrapper">
        <p><a class="button" href="{% url 'integral:nuevoPaciente' %}">Agregar paciente</a></p>
        <p><a class="button" href="{% url 'integral:index' %}">Regresar</a></p>
        <table>
          <thead>
            <tr>
              <td><b>Paciente</b></td>
              <td><b>Fecha Nacimiento</b></td>
              <td><b>Telefono</b></td>
              <td><b>Direccion</b></td>
              <td><b>Ver</b></td>
              <td><b>Eliminar</b></td>
            </tr>
          </thead>
          <tbody>
            {% for paciente in object_list %}
            <tr>
              <td>{{ paciente.nombre }}</td>
              <td>{{ paciente.fecha_nacimiento}}</td>
              <td>{{ paciente.telefono}}</td>
              <td>{{ paciente.direccion}}</td>
              <td><a class="button" href="{% url 'integral:detallePaciente' paciente.id %}">Ver</a></td>
              <td><a class="button" href="{% url 'integral:eliminarPaciente' paciente.id %}">Eliminar</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

clinica/integral/templates/integral/receta_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar la receta "{{ object }}"?
    <input type="submit" value="SI" />
    <a class="button" href="{% url 'integral:RecetaMedica' %}">No</a>
</form>
{% endblock content %}